<?php

namespace AppBundle\Repository;

/**
 * competencesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class competencesRepository extends \Doctrine\ORM\EntityRepository
{
}
