<?php

namespace AppBundle\Repository;

/**
 * ScolariteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScolariteRepository extends \Doctrine\ORM\EntityRepository
{
}
